name: CI Build, Test, Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python 3.11.4
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4

      - name: setup env and dependencies
        run: |
          pip install --upgrade pip
          python3.11.4 -m venv env
          pip install -r requirements.txt


  # test:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Check out the code
  #       uses: actions/checkout@v4

  #     - name: Set up Python 3.11
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.11

  #     - name: install pipenv
  #       run: |
  #         pip install pipenv

  #     - name: Install dependencies
  #       run: |
  #         pipenv install --dev

  #     - name: Test with pytest
  #       run: |
  #         pipenv run pytest

  # deploy:
  #   runs-on: ubuntu-latest

  #   needs: test

  #   steps:
  #     - name: Check out the code
  #       uses: actions/checkout@v3

  #     - name: Set up Python 3.11
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.11

  #     - name: install pipenv
  #       run: |
  #         pip install pipenv

  #     - name: Install dependencies
  #       run: |
  #         pipenv install --dev

  #     - name: create requirements
  #       run: |
  #         pipenv requirements > requirements.txt