name: CI Build, Test, Deploy

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: journal_app_test
          POSTGRES_USER: benhurst
          POSTGRES_PASSWORD: ''
          

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python 3.11.4
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4

      - name: Setup env
        run: |
          pip install --upgrade pip
          python3 -m venv env
          source env/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pytest
